# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#deploying hue
- name: deploy the hue parcel to all hosts
  cdh: action=deploy_parcel name=HUE_TRUSTEDANALYTICS version=3.9.0.1
  when: deploy_hue_trustedanalytics == true

- name: deploy hue master components
  cdh: action=deploy_base_roles service=hue host={{ groups['cdh-master'][0] }} 

- name: set hue service safety valve
  cdh: action=set_config entity=service service=hue name=hue_service_safety_valve value="{{ lookup('template', 'hue_service_safety_valve.j2') }}"
  when: deploy_hue_trustedanalytics == true

- name: set hue server role properties
  cdh: action=set_config entity=service service=hue name={{ item.name }} value={{ item.value }}
  with_items:
    - { name: 'hive_service', value: 'HIVE' }
    - { name: 'hbase_service', value: 'HBASE' }
    - { name: 'oozie_service', value: 'OOZIE' }
    - { name: 'hue_webhdfs', value: 'HDFS-HTTPFS-1' }
    - { name: 'database_host', value: "{{ groups['cdh-manager'][0] }}" }
    - { name: 'database_password', value: "{{ hive_mysql_root_password }}" }
    - { name: 'database_name', value: 'hue' }
    - { name: 'database_type', value: 'mysql' }
    - { name: 'database_user', value: 'hue' }

- name: start hue service
  cdh: action=service service=hue state=started

- wait_for: host={{ groups['cdh-master'][0] }} port=8888

- name: prepare hue users database to oauth integration
  shell: mysql -u root --password={{ hive_mysql_root_password }} -D hue -e 'ALTER TABLE auth_user MODIFY COLUMN username VARCHAR(255) NOT NULL;'

- name: create hue first user
  script: create_hue_superuser.py {{ groups['cdh-master'][0] }} {{ cf_kerberos_password }} && touch /var/hue_user_created creates=/var/hue_user_created
  when: deploy_hue_trustedanalytics == false
