# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#this playbook installs all of the components of the krb5 server
- name: install KRB5 base
  yum: pkg={{ item }} state=installed
  environment: proxy_env
  with_items:
    - krb5-server
    - openldap-clients

- name: copy kadm5.acl
  copy: src=kadm5.acl dest=/var/kerberos/krb5kdc/kadm5.acl
 
- name: copy kdc.conf
  copy: src=kdc.conf dest=/var/kerberos/krb5kdc/kdc.conf

- name: create the initial kerberos database
  shell: echo -e "{{ master_krb_pass }}\n{{ master_krb_pass }}" | kdb5_util create -s && touch /var/kerberos/db_created creates=/var/kerberos/db_created

#- name: create an admin for the administering the kerberos database
#  shell: echo -e "{{ kadmin_pass }}\n{{ kadmin_pass }}" | kadmin.local -q "addprinc kadmin/admin" && touch /var/kerberos/admin_created creates=/var/kerberos/admin_created

#- name: create an admin for administering by CDH
#  shell: echo -e "{{ kadmin_pass }}\n{{ kadmin_pass }}" | kadmin.local -q "addprinc cloudera-scm/admin" && touch /var/kerberos/cdh_admin_created creates=/var/kerberos/cdh_admin_created

- name: create users
  kadduser: name='{{ item.name }}' password='{{ item.pass }}'
  with_items:
    - { name: 'hdfs', pass: '{{ kadmin_pass }}' }
    - { name: 'hbase', pass: '{{ kadmin_pass }}' }
    - { name: 'cf', pass: '{{ cf_password }}' }
    - { name: 'kadmin/admin', pass: '{{ kadmin_pass }}' }
    - { name: 'cloudera-scm/admin', pass: '{{ kadmin_pass }}' }

- name: start kerberos services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - krb5kdc
    - kadmin
