# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- 
  name: "kerberos hack for arcengined startup"
  lineinfile: 
    dest: "/opt/arcadia/tools/arccluster/procmon/init.d/arcengine/start-arcengined-fg.sh"
    insertbefore: '^for\sARG\sin'
    line: 'ARCENGINED_ARGS="${ARCENGINED_ARGS} --kerberos_reinit_interval=60 --principal={{ arcadia.sysuser.name }}/{{ inventory_hostname }}@{{ arcadia.kerberos.realm }} --keytab_file={{ arcadia_user.home }}/{{ arcadia.kerberos.client_keytabfile }}"'
  when: kerberos_enabled|bool
-
  name: "set up arcadia cluster final definition"
  template:
    src: "this.j2"
    dest: "{{ arcadia_user.home }}/.acli/conf/clusters/this"
    owner: "{{ arcadia.sysuser.name }}"
    group: "{{ arcadia.sysuser.name }}"
    mode: "0644"
-
  name: "initiate arcadia cluster"
  command: "/usr/bin/acli cluster setactive this"
  sudo: "yes"
  sudo_user: "{{ arcadia.sysuser.name }}"
