# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#this playbook installs all of the dependencies required by both the cloudera manager and it's nodes
- name: calculate root partition size for AWS
  set_fact: ansible_root_size={{ ansible_devices.xvda.partitions.xvda1.sectors|int * ansible_devices.xvda.partitions.xvda1.sectorsize|int }}
  when: ansible_virtualization_type == 'xen'
  tags:
   - skip_on_vagrant
   - skip_on_one_node_install
   - skip_on_bare_metal

- name: calculate root partition size for Openstack
  set_fact: ansible_root_size={{ ansible_devices.vda.partitions.vda1.sectors|int * ansible_devices.vda.partitions.vda1.sectorsize|int }}
  when: ansible_virtualization_type == 'NA'
  tags:
   - skip_on_vagrant
   - skip_on_one_node_install
   - skip_on_bare_metal

- name: check root disk size
  fail: msg="The root partition has less than 20GB, ansible cannot continue"
  when: "{{ ansible_root_size|int < 21474836480 }}"
  tags:
    - skip_on_packer
    - skip_on_vagrant
    - skip_on_one_node_install
    - skip_on_bare_metal

- name: ensure custom facts directory exists
  file: path=/etc/ansible/facts.d recurse=yes state=directory

- name: distribute device info fact
  template: src=device_info.fact dest=/etc/ansible/facts.d/device_info.fact mode=0755

- name: reload ansible_local facts
  setup: filter=ansible_local

- name: Copy the Oracle JDK 8
  copy: src=java-jdk-1.8.0_72.rpm dest=/root/java-jdk-1.8.0_72.rpm

- name: Install the Oracle JDK 8
  yum: name=/root/java-jdk-1.8.0_72.rpm state=present

- name: set java home
  copy: src=java_env.sh dest=/etc/profile.d/java_env.sh owner=root group=root mode=0755

- name: create group on each worker machine
  group: name={{ item.name }} gid={{ item.gid }} system=yes
  with_items: cdh_work_groups

- name: create user on each machine
  user: name={{ item.name }} group={{ item.group }} uid={{ item.uid }} system=yes
  with_items: cdh_work_users

- name: Download nss binaries
  get_url: url={{ nss_binary_url }} dest=/root/zookeeper_nss.zip
  environment: proxy_env

- name: install nss module
  unarchive: src=/root/zookeeper_nss.zip dest=/ copy=no creates=/lib64/libnss_zk.so.2

- name: enable hgm nns passwd module
  lineinfile: 'dest=/etc/nsswitch.conf regexp="^passwd:" line="passwd: files zk"'

- name: enable hgm nns group module
  lineinfile: 'dest=/etc/nsswitch.conf regexp="^group:" line="group: files zk"'
